version: "3"
services: 
  mysql:
    image: mysql:5.7.16
    environment: 
    - "MYSQL_ROOT_PASSWORD=root"
    - "MYSQL_DATABASE=demo"
    - "MYSQL_USER=demo"
    - "MYSQL_PASSWORD=demo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
    - "./db:/var/lib/mysql"
    - "./master.cnf:/etc/mysql/my.cnf"
    ports:
    - "3306:3306"
  mysql2:
    image: mysql:5.7.16
    environment: 
    - "MYSQL_ROOT_PASSWORD=root"
    - "MYSQL_DATABASE=demo"
    - "MYSQL_USER=demo"
    - "MYSQL_PASSWORD=demo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
    - "./db2:/var/lib/mysql"
    - "./slave.cnf:/etc/mysql/my.cnf"
    ports:
    - "3307:3306"